
-- =====================================================
-- SEED DATA: Esercizi e Template (senza utenti auth)
-- =====================================================

-- Inserisci nuovi esercizi con video
INSERT INTO public.exercises (name, description, instructions, category, muscle_groups, equipment, difficulty_level, video_url, image_url, is_public) VALUES
-- FORZA
('Panca Inclinata con Manubri', 'Variante della panca piana che enfatizza la parte alta del petto', '1. Sdraiati su panca inclinata a 30-45 gradi\n2. Afferra i manubri\n3. Abbassa controllando fino al petto\n4. Spingi verso l''alto espirando', 'forza', ARRAY['petto','spalle','tricipiti'], ARRAY['panca inclinata','manubri'], 'intermedio', 'https://www.youtube.com/watch?v=8iPEnn-ltC8', 'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=400', true),
('Military Press', 'Esercizio fondamentale per le spalle con bilanciere', '1. Afferra il bilanciere oltre le spalle\n2. Spingi verso l''alto\n3. Estendi completamente le braccia\n4. Abbassa con controllo', 'forza', ARRAY['spalle','tricipiti','core'], ARRAY['bilanciere'], 'intermedio', 'https://www.youtube.com/watch?v=2yjwXTZQDDI', 'https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?w=400', true),
('Rematore con Bilanciere', 'Esercizio per lo spessore della schiena', '1. Inclinati in avanti schiena dritta\n2. Tira verso l''ombelico\n3. Stringi le scapole\n4. Abbassa con controllo', 'forza', ARRAY['dorsali','bicipiti','romboidi'], ARRAY['bilanciere'], 'intermedio', 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ', 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=400', true),
('Curl Bilanciere', 'Esercizio classico per i bicipiti', '1. In piedi con bilanciere\n2. Gomiti fissi ai fianchi\n3. Fletti le braccia\n4. Abbassa lentamente', 'forza', ARRAY['bicipiti','avambracci'], ARRAY['bilanciere'], 'principiante', 'https://www.youtube.com/watch?v=kwG2ipFRgfo', 'https://images.unsplash.com/photo-1581009146145-b5ef050c149a?w=400', true),
('French Press', 'Isolamento per i tricipiti', '1. Sdraiati su panca con bilanciere EZ\n2. Fletti i gomiti verso la fronte\n3. Estendi le braccia', 'forza', ARRAY['tricipiti'], ARRAY['bilanciere EZ','panca'], 'intermedio', 'https://www.youtube.com/watch?v=d_KZxkY_0cM', 'https://images.unsplash.com/photo-1530822847156-5df684ec5ee1?w=400', true),
('Lat Machine Presa Larga', 'Esercizio per l''ampiezza del dorsale', '1. Siediti alla lat machine\n2. Tira la barra verso il petto\n3. Stringi le scapole', 'forza', ARRAY['dorsali','bicipiti'], ARRAY['lat machine'], 'principiante', 'https://www.youtube.com/watch?v=CAwf7n6Luuc', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400', true),
('Leg Press', 'Esercizio per le gambe alla pressa', '1. Piedi alla larghezza spalle\n2. Abbassa fino a 90 gradi\n3. Spingi senza bloccare ginocchia', 'forza', ARRAY['quadricipiti','glutei','femorali'], ARRAY['leg press'], 'principiante', 'https://www.youtube.com/watch?v=IZxyjW7MPJQ', 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=400', true),
('Romanian Deadlift', 'Stacco rumeno per femorali e glutei', '1. Leggera flessione ginocchia\n2. Inclina il busto schiena dritta\n3. Risali contraendo i glutei', 'forza', ARRAY['femorali','glutei','lombari'], ARRAY['bilanciere'], 'intermedio', 'https://www.youtube.com/watch?v=JCXUYuzwNrM', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400', true),
('Affondi con Manubri', 'Esercizio unilaterale per gambe e glutei', '1. Fai un passo avanti lungo\n2. Abbassa il ginocchio posteriore\n3. Spingi indietro', 'forza', ARRAY['quadricipiti','glutei','femorali'], ARRAY['manubri'], 'intermedio', 'https://www.youtube.com/watch?v=D7KaRcUTQeE', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400', true),
-- CARDIO
('Burpees', 'Esercizio cardio total body ad alta intensità', '1. Abbassati in squat\n2. Salta indietro in plank\n3. Fai un push-up\n4. Salta verso l''alto', 'cardio', ARRAY['total body','core','gambe'], ARRAY['corpo libero'], 'avanzato', 'https://www.youtube.com/watch?v=dZgVxmf6jkA', 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?w=400', true),
('Mountain Climbers', 'Cardio dinamico in posizione plank', '1. Parti in plank\n2. Porta ginocchio al petto\n3. Alterna rapidamente', 'cardio', ARRAY['core','flessori anca','spalle'], ARRAY['corpo libero'], 'intermedio', 'https://www.youtube.com/watch?v=nmwgirgXLYM', 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=400', true),
('Jumping Jacks', 'Esercizio cardio classico', '1. Salta aprendo gambe e braccia\n2. Torna alla posizione iniziale\n3. Ripeti con ritmo', 'cardio', ARRAY['total body','spalle','polpacci'], ARRAY['corpo libero'], 'principiante', 'https://www.youtube.com/watch?v=c4DAnQ6DtF8', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400', true),
('Box Jump', 'Salto pliometrico su box', '1. Abbassati in mezzo squat\n2. Salta esplosivamente sul box\n3. Scendi con controllo', 'cardio', ARRAY['quadricipiti','glutei','polpacci'], ARRAY['box pliometrico'], 'avanzato', 'https://www.youtube.com/watch?v=52r_Ul5k03g', 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=400', true),
('High Knees', 'Corsa sul posto con ginocchia alte', '1. Solleva ginocchio verso il petto\n2. Alterna rapidamente\n3. Usa le braccia come nella corsa', 'cardio', ARRAY['flessori anca','core','polpacci'], ARRAY['corpo libero'], 'principiante', 'https://www.youtube.com/watch?v=D5z2IG0tZFk', 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400', true),
-- MOBILITA
('Cat-Cow Stretch', 'Mobilizzazione della colonna vertebrale', '1. A quattro zampe\n2. Inspira inarcando (mucca)\n3. Espira arrotondando (gatto)', 'mobilità', ARRAY['colonna','core'], ARRAY['tappetino'], 'principiante', 'https://www.youtube.com/watch?v=kqnua4rHVVA', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400', true),
('Hip Flexor Stretch', 'Allungamento dei flessori dell''anca', '1. In ginocchio con un piede avanti\n2. Spingi le anche in avanti\n3. Mantieni 30-60 secondi', 'mobilità', ARRAY['flessori anca','quadricipiti'], ARRAY['tappetino'], 'principiante', 'https://www.youtube.com/watch?v=YQmpO9VT2X4', 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400', true),
-- FUNCTIONAL
('Kettlebell Swing', 'Movimento balistico con kettlebell', '1. Piedi oltre larghezza spalle\n2. Esegui hike pass\n3. Estendi esplosivamente anche e ginocchia', 'funzionale', ARRAY['glutei','femorali','core','spalle'], ARRAY['kettlebell'], 'intermedio', 'https://www.youtube.com/watch?v=YSxHifyI6s8', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400', true),
('Turkish Get-Up', 'Alzata complessa dal pavimento', '1. Sdraiato con KB braccio esteso\n2. Rotola e alzati seguendo i passaggi\n3. Torna giù invertendo', 'funzionale', ARRAY['core','spalle','stabilizzatori'], ARRAY['kettlebell'], 'avanzato', 'https://www.youtube.com/watch?v=0bWRPC49-KI', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400', true),
('Battle Ropes Waves', 'Condizionamento con funi', '1. Afferra le funi\n2. Alterna le braccia creando onde\n3. Mantieni ritmo per 20-40 sec', 'funzionale', ARRAY['spalle','braccia','core'], ARRAY['battle ropes'], 'intermedio', 'https://www.youtube.com/watch?v=bFjQo4-gXkE', 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400', true),
('Farmers Walk', 'Trasporto carichi', '1. Afferra due KB pesanti\n2. Cammina con postura eretta\n3. Mantieni core attivo', 'funzionale', ARRAY['grip','trapezio','core','gambe'], ARRAY['kettlebell','manubri'], 'principiante', 'https://www.youtube.com/watch?v=Fkzk_RqlYig', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400', true),
('Medicine Ball Slam', 'Esercizio esplosivo con palla medica', '1. Palla sopra la testa\n2. Lancia a terra con forza\n3. Raccogli e ripeti', 'funzionale', ARRAY['core','spalle','dorsali'], ARRAY['palla medica'], 'intermedio', 'https://www.youtube.com/watch?v=jP7aCR1sdbQ', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400', true)
ON CONFLICT DO NOTHING;

-- Aggiorna esercizi esistenti con video URL
UPDATE public.exercises SET video_url = 'https://www.youtube.com/watch?v=rT7DgCr-3pg' WHERE name ILIKE '%squat%' AND video_url IS NULL;
UPDATE public.exercises SET video_url = 'https://www.youtube.com/watch?v=gRVjAtPip0Y' WHERE (name ILIKE '%panca%' OR name ILIKE '%bench%') AND video_url IS NULL;
UPDATE public.exercises SET video_url = 'https://www.youtube.com/watch?v=vthMCtgVtFw' WHERE (name ILIKE '%stacco%' OR name ILIKE '%deadlift%') AND video_url IS NULL;
