-- Fix nomi Drive (niente "Back lever · Back Lever Advanced") + pulizia catalogo palestra rimasto.
-- Non tocca esercizi privati PT (is_public = false).

UPDATE public.exercises SET name = 'Back lever · Advanced Pulls', description = 'Skill di leva posteriore alla sbarra. Variante: Advanced Pulls.', instructions = 'Esegui Back lever · Advanced Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever Advanced Pulls';
UPDATE public.exercises SET name = 'Back lever · Advanced', description = 'Skill di leva posteriore alla sbarra. Variante: Advanced.', instructions = 'Esegui Back lever · Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever Advanced';
UPDATE public.exercises SET name = 'Back lever · Full Pulls', description = 'Skill di leva posteriore alla sbarra. Variante: Full Pulls.', instructions = 'Esegui Back lever · Full Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever Full Pulls';
UPDATE public.exercises SET name = 'Back lever · Full', description = 'Skill di leva posteriore alla sbarra. Variante: Full.', instructions = 'Esegui Back lever · Full con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever Full';
UPDATE public.exercises SET name = 'Back lever · One Leg Advanced Pulls', description = 'Skill di leva posteriore alla sbarra. Variante: One Leg Advanced Pulls.', instructions = 'Esegui Back lever · One Leg Advanced Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever One Leg Advanced Pulls';
UPDATE public.exercises SET name = 'Back lever · One Leg Advanced', description = 'Skill di leva posteriore alla sbarra. Variante: One Leg Advanced.', instructions = 'Esegui Back lever · One Leg Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever One Leg Advanced';
UPDATE public.exercises SET name = 'Back lever · One Leg Pulls', description = 'Skill di leva posteriore alla sbarra. Variante: One Leg Pulls.', instructions = 'Esegui Back lever · One Leg Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever One Leg Pulls';
UPDATE public.exercises SET name = 'Back lever · One Leg', description = 'Skill di leva posteriore alla sbarra. Variante: One Leg.', instructions = 'Esegui Back lever · One Leg con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever One Leg';
UPDATE public.exercises SET name = 'Back lever · Straddle Pulls', description = 'Skill di leva posteriore alla sbarra. Variante: Straddle Pulls.', instructions = 'Esegui Back lever · Straddle Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever Straddle Pulls';
UPDATE public.exercises SET name = 'Back lever · Straddle', description = 'Skill di leva posteriore alla sbarra. Variante: Straddle.', instructions = 'Esegui Back lever · Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever Straddle';
UPDATE public.exercises SET name = 'Back lever · Tuck Pulls', description = 'Skill di leva posteriore alla sbarra. Variante: Tuck Pulls.', instructions = 'Esegui Back lever · Tuck Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever Tuck Pulls';
UPDATE public.exercises SET name = 'Back lever · Tuck', description = 'Skill di leva posteriore alla sbarra. Variante: Tuck.', instructions = 'Esegui Back lever · Tuck con controllo, scapole attive e core chiuso. Progressione della famiglia Back lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Back lever · Back Lever Tuck';
UPDATE public.exercises SET name = 'Bar muscle up · Box Assisted', description = 'Transizione pull-up → dip alla sbarra. Variante: Box Assisted.', instructions = 'Esegui Bar muscle up · Box Assisted con controllo, scapole attive e core chiuso. Progressione della famiglia Bar muscle up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Bar muscle up · Box Assisted Muscle Up';
UPDATE public.exercises SET name = 'Bar muscle up · L Sit', description = 'Transizione pull-up → dip alla sbarra. Variante: L Sit.', instructions = 'Esegui Bar muscle up · L Sit con controllo, scapole attive e core chiuso. Progressione della famiglia Bar muscle up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Bar muscle up · L Sit Muscle Up';
UPDATE public.exercises SET name = 'Bar muscle up', description = 'Transizione pull-up → dip alla sbarra.', instructions = 'Esegui Bar muscle up con controllo, scapole attive e core chiuso. Progressione della famiglia Bar muscle up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Bar muscle up · Muscle Up';
UPDATE public.exercises SET name = 'Core · V Ups', description = 'Lavoro di core a corpo libero o sbarra. Variante: V Ups.', instructions = 'Esegui Core · V Ups con controllo, scapole attive e core chiuso. Progressione della famiglia Core. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Core · V-Ups';
UPDATE public.exercises SET name = 'Core · Tuck V Ups', description = 'Lavoro di core a corpo libero o sbarra. Variante: Tuck V Ups.', instructions = 'Esegui Core · Tuck V Ups con controllo, scapole attive e core chiuso. Progressione della famiglia Core. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Core · Tuck V-Ups';
UPDATE public.exercises SET name = 'Dip · Elevated Foot Dips', description = 'Dip su parallele, sbarra o anelli. Variante: Elevated Foot Dips.', instructions = 'Esegui Dip · Elevated Foot Dips con controllo, scapole attive e core chiuso. Progressione della famiglia Dip. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Dip · Elevated-Foot Dips';
UPDATE public.exercises SET name = 'Dragon press · Advanced', description = 'Pressa a corpo libero tipo dragon press. Variante: Advanced.', instructions = 'Esegui Dragon press · Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Dragon press. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Dragon press · Dragon Press Advanced';
UPDATE public.exercises SET name = 'Dragon press · Full', description = 'Pressa a corpo libero tipo dragon press. Variante: Full.', instructions = 'Esegui Dragon press · Full con controllo, scapole attive e core chiuso. Progressione della famiglia Dragon press. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Dragon press · Dragon Press Full';
UPDATE public.exercises SET name = 'Dragon press · One Leg', description = 'Pressa a corpo libero tipo dragon press. Variante: One Leg.', instructions = 'Esegui Dragon press · One Leg con controllo, scapole attive e core chiuso. Progressione della famiglia Dragon press. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Dragon press · Dragon Press One Leg';
UPDATE public.exercises SET name = 'Dragon press · Straddle', description = 'Pressa a corpo libero tipo dragon press. Variante: Straddle.', instructions = 'Esegui Dragon press · Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia Dragon press. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Dragon press · Dragon Press Straddle';
UPDATE public.exercises SET name = 'Dragon press · Tuck', description = 'Pressa a corpo libero tipo dragon press. Variante: Tuck.', instructions = 'Esegui Dragon press · Tuck con controllo, scapole attive e core chiuso. Progressione della famiglia Dragon press. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Dragon press · Dragon Press Tuck';
UPDATE public.exercises SET name = 'Front lever · Advanced Pull Up', description = 'Skill di leva anteriore alla sbarra. Variante: Advanced Pull Up.', instructions = 'Esegui Front lever · Advanced Pull Up con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Advanced Pull Up';
UPDATE public.exercises SET name = 'Front lever · Advanced Pulls', description = 'Skill di leva anteriore alla sbarra. Variante: Advanced Pulls.', instructions = 'Esegui Front lever · Advanced Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Advanced Pulls';
UPDATE public.exercises SET name = 'Front lever · Advanced Raises', description = 'Skill di leva anteriore alla sbarra. Variante: Advanced Raises.', instructions = 'Esegui Front lever · Advanced Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Advanced Raises';
UPDATE public.exercises SET name = 'Front lever · Advanced', description = 'Skill di leva anteriore alla sbarra. Variante: Advanced.', instructions = 'Esegui Front lever · Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Advanced';
UPDATE public.exercises SET name = 'Front lever · Full Pull Up', description = 'Skill di leva anteriore alla sbarra. Variante: Full Pull Up.', instructions = 'Esegui Front lever · Full Pull Up con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Full Pull Up';
UPDATE public.exercises SET name = 'Front lever · Full Pulls', description = 'Skill di leva anteriore alla sbarra. Variante: Full Pulls.', instructions = 'Esegui Front lever · Full Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Full Pulls';
UPDATE public.exercises SET name = 'Front lever · Full Raises', description = 'Skill di leva anteriore alla sbarra. Variante: Full Raises.', instructions = 'Esegui Front lever · Full Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Full Raises';
UPDATE public.exercises SET name = 'Front lever · Full', description = 'Skill di leva anteriore alla sbarra. Variante: Full.', instructions = 'Esegui Front lever · Full con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Full';
UPDATE public.exercises SET name = 'Front lever · One Leg Pull Up', description = 'Skill di leva anteriore alla sbarra. Variante: One Leg Pull Up.', instructions = 'Esegui Front lever · One Leg Pull Up con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever One Leg Pull Up';
UPDATE public.exercises SET name = 'Front lever · One Leg Pulls', description = 'Skill di leva anteriore alla sbarra. Variante: One Leg Pulls.', instructions = 'Esegui Front lever · One Leg Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever One Leg Pulls';
UPDATE public.exercises SET name = 'Front lever · One Leg Raises', description = 'Skill di leva anteriore alla sbarra. Variante: One Leg Raises.', instructions = 'Esegui Front lever · One Leg Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever One Leg Raises';
UPDATE public.exercises SET name = 'Front lever · One Leg', description = 'Skill di leva anteriore alla sbarra. Variante: One Leg.', instructions = 'Esegui Front lever · One Leg con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever One Leg';
UPDATE public.exercises SET name = 'Front lever · Pulses', description = 'Skill di leva anteriore alla sbarra. Variante: Pulses.', instructions = 'Esegui Front lever · Pulses con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Pulses';
UPDATE public.exercises SET name = 'Front lever · Straddle Pull Up', description = 'Skill di leva anteriore alla sbarra. Variante: Straddle Pull Up.', instructions = 'Esegui Front lever · Straddle Pull Up con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Straddle Pull Up';
UPDATE public.exercises SET name = 'Front lever · Straddle Raises', description = 'Skill di leva anteriore alla sbarra. Variante: Straddle Raises.', instructions = 'Esegui Front lever · Straddle Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Straddle Raises';
UPDATE public.exercises SET name = 'Front lever · Straddle', description = 'Skill di leva anteriore alla sbarra. Variante: Straddle.', instructions = 'Esegui Front lever · Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Straddle';
UPDATE public.exercises SET name = 'Front lever · Touch Advanced', description = 'Skill di leva anteriore alla sbarra. Variante: Touch Advanced.', instructions = 'Esegui Front lever · Touch Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Touch Advanced';
UPDATE public.exercises SET name = 'Front lever · Touch Full', description = 'Skill di leva anteriore alla sbarra. Variante: Touch Full.', instructions = 'Esegui Front lever · Touch Full con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Touch Full';
UPDATE public.exercises SET name = 'Front lever · Touch One Leg Advanced', description = 'Skill di leva anteriore alla sbarra. Variante: Touch One Leg Advanced.', instructions = 'Esegui Front lever · Touch One Leg Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Touch One Leg Advanced';
UPDATE public.exercises SET name = 'Front lever · Touch Straddle', description = 'Skill di leva anteriore alla sbarra. Variante: Touch Straddle.', instructions = 'Esegui Front lever · Touch Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Touch Straddle';
UPDATE public.exercises SET name = 'Front lever · Tuck Pulls', description = 'Skill di leva anteriore alla sbarra. Variante: Tuck Pulls.', instructions = 'Esegui Front lever · Tuck Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Tuck Pulls';
UPDATE public.exercises SET name = 'Front lever · Tuck', description = 'Skill di leva anteriore alla sbarra. Variante: Tuck.', instructions = 'Esegui Front lever · Tuck con controllo, scapole attive e core chiuso. Progressione della famiglia Front lever. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Front lever · Front Lever Tuck';
UPDATE public.exercises SET name = 'Handstand · Diagonal Wall Lean', description = 'Verticale e progressioni alla parete. Variante: Diagonal Wall Lean.', instructions = 'Esegui Handstand · Diagonal Wall Lean con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Diagonal Wall Lean Handstand';
UPDATE public.exercises SET name = 'Handstand · Half Lay', description = 'Verticale e progressioni alla parete. Variante: Half Lay.', instructions = 'Esegui Handstand · Half Lay con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Handstand Half Lay';
UPDATE public.exercises SET name = 'Handstand · One Leg', description = 'Verticale e progressioni alla parete. Variante: One Leg.', instructions = 'Esegui Handstand · One Leg con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Handstand One Leg';
UPDATE public.exercises SET name = 'Handstand · Straddle To Full', description = 'Verticale e progressioni alla parete. Variante: Straddle To Full.', instructions = 'Esegui Handstand · Straddle To Full con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Handstand Straddle To Full';
UPDATE public.exercises SET name = 'Handstand · Wall Pike Position', description = 'Verticale e progressioni alla parete. Variante: Wall Pike Position.', instructions = 'Esegui Handstand · Wall Pike Position con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Handstand Wall Pike Position';
UPDATE public.exercises SET name = 'Handstand', description = 'Verticale e progressioni alla parete.', instructions = 'Esegui Handstand con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Handstand';
UPDATE public.exercises SET name = 'Handstand · L Handstand Assisted', description = 'Verticale e progressioni alla parete. Variante: L Handstand Assisted.', instructions = 'Esegui Handstand · L Handstand Assisted con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · L-Handstand Assisted';
UPDATE public.exercises SET name = 'Handstand · L Handstand Kick Ups', description = 'Verticale e progressioni alla parete. Variante: L Handstand Kick Ups.', instructions = 'Esegui Handstand · L Handstand Kick Ups con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · L-Handstand Kick Ups';
UPDATE public.exercises SET name = 'Handstand · V Position', description = 'Verticale e progressioni alla parete. Variante: V Position.', instructions = 'Esegui Handstand · V Position con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · V-Position';
UPDATE public.exercises SET name = 'Handstand · Wall Facing', description = 'Verticale e progressioni alla parete. Variante: Wall Facing.', instructions = 'Esegui Handstand · Wall Facing con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Wall Facing Handstand';
UPDATE public.exercises SET name = 'Handstand · Wall L Handstand Kick Ups', description = 'Verticale e progressioni alla parete. Variante: Wall L Handstand Kick Ups.', instructions = 'Esegui Handstand · Wall L Handstand Kick Ups con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Wall L-Handstand Kick Ups';
UPDATE public.exercises SET name = 'Handstand · Wall L', description = 'Verticale e progressioni alla parete. Variante: Wall L.', instructions = 'Esegui Handstand · Wall L con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Wall L-Handstand';
UPDATE public.exercises SET name = 'Handstand · Wall Facing Handstand Alternating Leg Lifts', description = 'Verticale e progressioni alla parete. Variante: Wall Facing Handstand Alternating Leg Lifts.', instructions = 'Esegui Handstand · Wall Facing Handstand Alternating Leg Lifts con controllo, scapole attive e core chiuso. Progressione della famiglia Handstand. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Handstand · Wall-Facing Handstand Alternating Leg Lifts';
UPDATE public.exercises SET name = 'Hspu · Back To Wall On Parallettes', description = 'Piegamenti in verticale (HSPU). Variante: Back To Wall On Parallettes.', instructions = 'Esegui Hspu · Back To Wall On Parallettes con controllo, scapole attive e core chiuso. Progressione della famiglia Hspu. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Hspu · HSPU Back To Wall On Parallettes';
UPDATE public.exercises SET name = 'Hspu · Back To Wall', description = 'Piegamenti in verticale (HSPU). Variante: Back To Wall.', instructions = 'Esegui Hspu · Back To Wall con controllo, scapole attive e core chiuso. Progressione della famiglia Hspu. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Hspu · HSPU Back To Wall';
UPDATE public.exercises SET name = 'Hspu · Eccentric', description = 'Piegamenti in verticale (HSPU). Variante: Eccentric.', instructions = 'Esegui Hspu · Eccentric con controllo, scapole attive e core chiuso. Progressione della famiglia Hspu. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Hspu · HSPU Eccentric';
UPDATE public.exercises SET name = 'Hspu · On Prallelettes', description = 'Piegamenti in verticale (HSPU). Variante: On Prallelettes.', instructions = 'Esegui Hspu · On Prallelettes con controllo, scapole attive e core chiuso. Progressione della famiglia Hspu. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Hspu · HSPU On Prallelettes';
UPDATE public.exercises SET name = 'Hspu · Straddle', description = 'Piegamenti in verticale (HSPU). Variante: Straddle.', instructions = 'Esegui Hspu · Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia Hspu. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Hspu · HSPU Straddle';
UPDATE public.exercises SET name = 'Hspu · Wall Facing On Parallettes', description = 'Piegamenti in verticale (HSPU). Variante: Wall Facing On Parallettes.', instructions = 'Esegui Hspu · Wall Facing On Parallettes con controllo, scapole attive e core chiuso. Progressione della famiglia Hspu. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Hspu · HSPU Wall Facing On Parallettes';
UPDATE public.exercises SET name = 'Hspu · Pyke Push Up', description = 'Piegamenti in verticale (HSPU). Variante: Pyke Push Up.', instructions = 'Esegui Hspu · Pyke Push Up con controllo, scapole attive e core chiuso. Progressione della famiglia Hspu. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Hspu · Pyke Push-Up';
UPDATE public.exercises SET name = 'Hspu · V Push Up', description = 'Piegamenti in verticale (HSPU). Variante: V Push Up.', instructions = 'Esegui Hspu · V Push Up con controllo, scapole attive e core chiuso. Progressione della famiglia Hspu. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Hspu · V-Push Up';
UPDATE public.exercises SET name = 'Human flag · Full Raises', description = 'Bandiera umana su palo verticale. Variante: Full Raises.', instructions = 'Esegui Human flag · Full Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Human flag. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Human flag · Human Flag Full Raises';
UPDATE public.exercises SET name = 'Human flag · Half Lay', description = 'Bandiera umana su palo verticale. Variante: Half Lay.', instructions = 'Esegui Human flag · Half Lay con controllo, scapole attive e core chiuso. Progressione della famiglia Human flag. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Human flag · Human Flag Half Lay';
UPDATE public.exercises SET name = 'Human flag · Lay Raises', description = 'Bandiera umana su palo verticale. Variante: Lay Raises.', instructions = 'Esegui Human flag · Lay Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Human flag. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Human flag · Human Flag Lay Raises';
UPDATE public.exercises SET name = 'Human flag · Straddle Raises', description = 'Bandiera umana su palo verticale. Variante: Straddle Raises.', instructions = 'Esegui Human flag · Straddle Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Human flag. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Human flag · Human Flag Straddle Raises';
UPDATE public.exercises SET name = 'Human flag · Straddle', description = 'Bandiera umana su palo verticale. Variante: Straddle.', instructions = 'Esegui Human flag · Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia Human flag. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Human flag · Human Flag Straddle';
UPDATE public.exercises SET name = 'Human flag', description = 'Bandiera umana su palo verticale.', instructions = 'Esegui Human flag con controllo, scapole attive e core chiuso. Progressione della famiglia Human flag. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Human flag · Human Flag';
UPDATE public.exercises SET name = 'Iron cross · Assisted', description = 'Croce di ferro agli anelli. Variante: Assisted.', instructions = 'Esegui Iron cross · Assisted con controllo, scapole attive e core chiuso. Progressione della famiglia Iron cross. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Iron cross · Iron Cross Assisted';
UPDATE public.exercises SET name = 'Iron cross · Eccentric', description = 'Croce di ferro agli anelli. Variante: Eccentric.', instructions = 'Esegui Iron cross · Eccentric con controllo, scapole attive e core chiuso. Progressione della famiglia Iron cross. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Iron cross · Iron Cross Eccentric';
UPDATE public.exercises SET name = 'Iron cross · Half', description = 'Croce di ferro agli anelli. Variante: Half.', instructions = 'Esegui Iron cross · Half con controllo, scapole attive e core chiuso. Progressione della famiglia Iron cross. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Iron cross · Iron Cross Half';
UPDATE public.exercises SET name = 'Iron cross · Pulls', description = 'Croce di ferro agli anelli. Variante: Pulls.', instructions = 'Esegui Iron cross · Pulls con controllo, scapole attive e core chiuso. Progressione della famiglia Iron cross. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Iron cross · Iron Cross Pulls';
UPDATE public.exercises SET name = 'Iron cross', description = 'Croce di ferro agli anelli.', instructions = 'Esegui Iron cross con controllo, scapole attive e core chiuso. Progressione della famiglia Iron cross. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Iron cross · Iron Cross';
UPDATE public.exercises SET name = 'L-sit · Alternating Leg L Sit Extension', description = 'L-sit su parallele o sbarre. Variante: Alternating Leg L Sit Extension.', instructions = 'Esegui L-sit · Alternating Leg L Sit Extension con controllo, scapole attive e core chiuso. Progressione della famiglia L-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'L-sit · Alternating Leg L-sit Extension';
UPDATE public.exercises SET name = 'L-sit · Dinamic', description = 'L-sit su parallele o sbarre. Variante: Dinamic.', instructions = 'Esegui L-sit · Dinamic con controllo, scapole attive e core chiuso. Progressione della famiglia L-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'L-sit · Dinamic L-sit';
UPDATE public.exercises SET name = 'L-sit · Advanced', description = 'L-sit su parallele o sbarre. Variante: Advanced.', instructions = 'Esegui L-sit · Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia L-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'L-sit · L-sit Advanced';
UPDATE public.exercises SET name = 'L-sit · Full To Straddle', description = 'L-sit su parallele o sbarre. Variante: Full To Straddle.', instructions = 'Esegui L-sit · Full To Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia L-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'L-sit · L-sit Full To Straddle';
UPDATE public.exercises SET name = 'L-sit · Tuck', description = 'L-sit su parallele o sbarre. Variante: Tuck.', instructions = 'Esegui L-sit · Tuck con controllo, scapole attive e core chiuso. Progressione della famiglia L-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'L-sit · L-sit Tuck';
UPDATE public.exercises SET name = 'L-sit', description = 'L-sit su parallele o sbarre.', instructions = 'Esegui L-sit con controllo, scapole attive e core chiuso. Progressione della famiglia L-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'L-sit · L-sit';
UPDATE public.exercises SET name = 'Maltese · Straddle', description = 'Maltese / lean avanzato. Variante: Straddle.', instructions = 'Esegui Maltese · Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia Maltese. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Maltese · Maltese Straddle';
UPDATE public.exercises SET name = 'Maltese', description = 'Maltese / lean avanzato.', instructions = 'Esegui Maltese con controllo, scapole attive e core chiuso. Progressione della famiglia Maltese. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Maltese · Maltese';
UPDATE public.exercises SET name = 'Oap · Assisted', description = 'Trazione a un braccio e progressioni (OAP/OAC). Variante: Assisted.', instructions = 'Esegui Oap · Assisted con controllo, scapole attive e core chiuso. Progressione della famiglia Oap. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Oap · OAP Assisted';
UPDATE public.exercises SET name = 'Oap · Eccentric', description = 'Trazione a un braccio e progressioni (OAP/OAC). Variante: Eccentric.', instructions = 'Esegui Oap · Eccentric con controllo, scapole attive e core chiuso. Progressione della famiglia Oap. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Oap · OAP Eccentric';
UPDATE public.exercises SET name = 'Oap', description = 'Trazione a un braccio e progressioni (OAP/OAC).', instructions = 'Esegui Oap con controllo, scapole attive e core chiuso. Progressione della famiglia Oap. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Oap · OAP';
UPDATE public.exercises SET name = 'Planche · Advanced Push Up', description = 'Planche e progressioni (tuck, straddle, full). Variante: Advanced Push Up.', instructions = 'Esegui Planche · Advanced Push Up con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Advanced Push-Up';
UPDATE public.exercises SET name = 'Planche · Advanced', description = 'Planche e progressioni (tuck, straddle, full). Variante: Advanced.', instructions = 'Esegui Planche · Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Advanced';
UPDATE public.exercises SET name = 'Planche · Full Press', description = 'Planche e progressioni (tuck, straddle, full). Variante: Full Press.', instructions = 'Esegui Planche · Full Press con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Full Press';
UPDATE public.exercises SET name = 'Planche · Full', description = 'Planche e progressioni (tuck, straddle, full). Variante: Full.', instructions = 'Esegui Planche · Full con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Full';
UPDATE public.exercises SET name = 'Planche · Lean Push Up', description = 'Planche e progressioni (tuck, straddle, full). Variante: Lean Push Up.', instructions = 'Esegui Planche · Lean Push Up con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Lean Push-Up';
UPDATE public.exercises SET name = 'Planche · Lean Rocks', description = 'Planche e progressioni (tuck, straddle, full). Variante: Lean Rocks.', instructions = 'Esegui Planche · Lean Rocks con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Lean Rocks';
UPDATE public.exercises SET name = 'Planche · Lean', description = 'Planche e progressioni (tuck, straddle, full). Variante: Lean.', instructions = 'Esegui Planche · Lean con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Lean';
UPDATE public.exercises SET name = 'Planche · Lift Offs', description = 'Planche e progressioni (tuck, straddle, full). Variante: Lift Offs.', instructions = 'Esegui Planche · Lift Offs con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Lift-Offs';
UPDATE public.exercises SET name = 'Planche · Open Advanced', description = 'Planche e progressioni (tuck, straddle, full). Variante: Open Advanced.', instructions = 'Esegui Planche · Open Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Open Advanced';
UPDATE public.exercises SET name = 'Planche · Open Tuck', description = 'Planche e progressioni (tuck, straddle, full). Variante: Open Tuck.', instructions = 'Esegui Planche · Open Tuck con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Open Tuck';
UPDATE public.exercises SET name = 'Planche · Straddle Press', description = 'Planche e progressioni (tuck, straddle, full). Variante: Straddle Press.', instructions = 'Esegui Planche · Straddle Press con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Straddle Press';
UPDATE public.exercises SET name = 'Planche · Straddle', description = 'Planche e progressioni (tuck, straddle, full). Variante: Straddle.', instructions = 'Esegui Planche · Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Straddle';
UPDATE public.exercises SET name = 'Planche · Tuck Push Up', description = 'Planche e progressioni (tuck, straddle, full). Variante: Tuck Push Up.', instructions = 'Esegui Planche · Tuck Push Up con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Tuck Push-Up';
UPDATE public.exercises SET name = 'Planche · Tuck To Advanced', description = 'Planche e progressioni (tuck, straddle, full). Variante: Tuck To Advanced.', instructions = 'Esegui Planche · Tuck To Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Tuck To Advanced';
UPDATE public.exercises SET name = 'Planche · Tuck', description = 'Planche e progressioni (tuck, straddle, full). Variante: Tuck.', instructions = 'Esegui Planche · Tuck con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Planche Tuck';
UPDATE public.exercises SET name = 'Planche · Shoulder', description = 'Planche e progressioni (tuck, straddle, full). Variante: Shoulder.', instructions = 'Esegui Planche · Shoulder con controllo, scapole attive e core chiuso. Progressione della famiglia Planche. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Planche · Shoulder Planche';
UPDATE public.exercises SET name = 'Pull up · Chin Up', description = 'Trazioni e varianti di presa. Variante: Chin Up.', instructions = 'Esegui Pull up · Chin Up con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Chin-Up';
UPDATE public.exercises SET name = 'Pull up · Close Chin Up', description = 'Trazioni e varianti di presa. Variante: Close Chin Up.', instructions = 'Esegui Pull up · Close Chin Up con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Close Chin-Up';
UPDATE public.exercises SET name = 'Pull up · Close', description = 'Trazioni e varianti di presa. Variante: Close.', instructions = 'Esegui Pull up · Close con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Close Pull Up';
UPDATE public.exercises SET name = 'Pull up · Eccentric Chin Up', description = 'Trazioni e varianti di presa. Variante: Eccentric Chin Up.', instructions = 'Esegui Pull up · Eccentric Chin Up con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Eccentric Chin-Up';
UPDATE public.exercises SET name = 'Pull up · Eccentric', description = 'Trazioni e varianti di presa. Variante: Eccentric.', instructions = 'Esegui Pull up · Eccentric con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Eccentric Pull Up';
UPDATE public.exercises SET name = 'Pull up · Iso Chin Up 90°', description = 'Trazioni e varianti di presa. Variante: Iso Chin Up 90°.', instructions = 'Esegui Pull up · Iso Chin Up 90° con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Iso Chin-Up 90°';
UPDATE public.exercises SET name = 'Pull up · Iso Chin Up', description = 'Trazioni e varianti di presa. Variante: Iso Chin Up.', instructions = 'Esegui Pull up · Iso Chin Up con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Iso Chin-Up';
UPDATE public.exercises SET name = 'Pull up · Mixed Grip', description = 'Trazioni e varianti di presa. Variante: Mixed Grip.', instructions = 'Esegui Pull up · Mixed Grip con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Mixed Grip Pull Up';
UPDATE public.exercises SET name = 'Pull up · Neutral Grip', description = 'Trazioni e varianti di presa. Variante: Neutral Grip.', instructions = 'Esegui Pull up · Neutral Grip con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Neutral Grip Pull Up';
UPDATE public.exercises SET name = 'Pull up', description = 'Trazioni e varianti di presa.', instructions = 'Esegui Pull up con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Pull Up';
UPDATE public.exercises SET name = 'Pull up · Ring', description = 'Trazioni e varianti di presa. Variante: Ring.', instructions = 'Esegui Pull up · Ring con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Ring Pull Up';
UPDATE public.exercises SET name = 'Pull up · Wide', description = 'Trazioni e varianti di presa. Variante: Wide.', instructions = 'Esegui Pull up · Wide con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Wide Pull Up';
UPDATE public.exercises SET name = 'Pull up · Australian', description = 'Trazioni e varianti di presa. Variante: Australian.', instructions = 'Esegui Pull up · Australian con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Australian Pull-Up';
UPDATE public.exercises SET name = 'Pull up · Foot Assisted', description = 'Trazioni e varianti di presa. Variante: Foot Assisted.', instructions = 'Esegui Pull up · Foot Assisted con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Foot-Assisted Pull-Up';
UPDATE public.exercises SET name = 'Pull up · Horizontal', description = 'Trazioni e varianti di presa. Variante: Horizontal.', instructions = 'Esegui Pull up · Horizontal con controllo, scapole attive e core chiuso. Progressione della famiglia Pull up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Pull up · Horizontal Pull-Up';
UPDATE public.exercises SET name = 'Push Up · Archer', description = 'Piegamenti e varianti. Variante: Archer.', instructions = 'Esegui Push Up · Archer con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Archer Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Decline', description = 'Piegamenti e varianti. Variante: Decline.', instructions = 'Esegui Push Up · Decline con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Decline Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Diamond', description = 'Piegamenti e varianti. Variante: Diamond.', instructions = 'Esegui Push Up · Diamond con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Diamond Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Knee', description = 'Piegamenti e varianti. Variante: Knee.', instructions = 'Esegui Push Up · Knee con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Knee Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Parallette', description = 'Piegamenti e varianti. Variante: Parallette.', instructions = 'Esegui Push Up · Parallette con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Parallette Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Plio', description = 'Piegamenti e varianti. Variante: Plio.', instructions = 'Esegui Push Up · Plio con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Plio Push-Ups';
UPDATE public.exercises SET name = 'Push Up', description = 'Piegamenti e varianti.', instructions = 'Esegui Push Up con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Ring', description = 'Piegamenti e varianti. Variante: Ring.', instructions = 'Esegui Push Up · Ring con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Ring Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Russian', description = 'Piegamenti e varianti. Variante: Russian.', instructions = 'Esegui Push Up · Russian con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Russian Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Scapular', description = 'Piegamenti e varianti. Variante: Scapular.', instructions = 'Esegui Push Up · Scapular con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Scapular Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Staggered', description = 'Piegamenti e varianti. Variante: Staggered.', instructions = 'Esegui Push Up · Staggered con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Staggered Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Supinated Ring', description = 'Piegamenti e varianti. Variante: Supinated Ring.', instructions = 'Esegui Push Up · Supinated Ring con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Supinated Ring Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Tiger', description = 'Piegamenti e varianti. Variante: Tiger.', instructions = 'Esegui Push Up · Tiger con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Tiger Push-Ups';
UPDATE public.exercises SET name = 'Push Up · Wide', description = 'Piegamenti e varianti. Variante: Wide.', instructions = 'Esegui Push Up · Wide con controllo, scapole attive e core chiuso. Progressione della famiglia Push Up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Push Up · Wide Push-Ups';
UPDATE public.exercises SET name = 'Ring muscle up · Eccentric', description = 'Muscle-up agli anelli e false grip. Variante: Eccentric.', instructions = 'Esegui Ring muscle up · Eccentric con controllo, scapole attive e core chiuso. Progressione della famiglia Ring muscle up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Ring muscle up · Eccentric Ring Muscle Up';
UPDATE public.exercises SET name = 'Ring muscle up · Assisted', description = 'Muscle-up agli anelli e false grip. Variante: Assisted.', instructions = 'Esegui Ring muscle up · Assisted con controllo, scapole attive e core chiuso. Progressione della famiglia Ring muscle up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Ring muscle up · Ring Muscle Up Assisted';
UPDATE public.exercises SET name = 'Ring muscle up', description = 'Muscle-up agli anelli e false grip.', instructions = 'Esegui Ring muscle up con controllo, scapole attive e core chiuso. Progressione della famiglia Ring muscle up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Ring muscle up · Ring Muscle Up';
UPDATE public.exercises SET name = 'Stretching · Cross Body Shoulder', description = 'Allungamento e mobilità. Variante: Cross Body Shoulder.', instructions = 'Esegui Stretching · Cross Body Shoulder con controllo, scapole attive e core chiuso. Progressione della famiglia Stretching. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Stretching · Cross-Body Shoulder';
UPDATE public.exercises SET name = 'Stretching · Cross Legged Standing Forward Fold', description = 'Allungamento e mobilità. Variante: Cross Legged Standing Forward Fold.', instructions = 'Esegui Stretching · Cross Legged Standing Forward Fold con controllo, scapole attive e core chiuso. Progressione della famiglia Stretching. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Stretching · Cross-Legged Standing Forward Fold';
UPDATE public.exercises SET name = 'Stretching · Shoulder Width Standing Forward Fold', description = 'Allungamento e mobilità. Variante: Shoulder Width Standing Forward Fold.', instructions = 'Esegui Stretching · Shoulder Width Standing Forward Fold con controllo, scapole attive e core chiuso. Progressione della famiglia Stretching. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Stretching · Shoulder-Width Standing Forward Fold';
UPDATE public.exercises SET name = 'Ted · Eccentric', description = 'Skill TED (progressione anelli). Variante: Eccentric.', instructions = 'Esegui Ted · Eccentric con controllo, scapole attive e core chiuso. Progressione della famiglia Ted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Ted · Eccentric TED';
UPDATE public.exercises SET name = 'Ted · Half', description = 'Skill TED (progressione anelli). Variante: Half.', instructions = 'Esegui Ted · Half con controllo, scapole attive e core chiuso. Progressione della famiglia Ted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Ted · Half TED';
UPDATE public.exercises SET name = 'Ted · Assisted', description = 'Skill TED (progressione anelli). Variante: Assisted.', instructions = 'Esegui Ted · Assisted con controllo, scapole attive e core chiuso. Progressione della famiglia Ted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Ted · TED Assisted';
UPDATE public.exercises SET name = 'Ted · Iso', description = 'Skill TED (progressione anelli). Variante: Iso.', instructions = 'Esegui Ted · Iso con controllo, scapole attive e core chiuso. Progressione della famiglia Ted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Ted · TED Iso';
UPDATE public.exercises SET name = 'Ted', description = 'Skill TED (progressione anelli).', instructions = 'Esegui Ted con controllo, scapole attive e core chiuso. Progressione della famiglia Ted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Ted · TED';
UPDATE public.exercises SET name = 'V-sit · Straddle', description = 'V-sit e compressioni. Variante: Straddle.', instructions = 'Esegui V-sit · Straddle con controllo, scapole attive e core chiuso. Progressione della famiglia V-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'V-sit · V-sit Straddle';
UPDATE public.exercises SET name = 'V-sit · Tuck Alternating Leg Extensions', description = 'V-sit e compressioni. Variante: Tuck Alternating Leg Extensions.', instructions = 'Esegui V-sit · Tuck Alternating Leg Extensions con controllo, scapole attive e core chiuso. Progressione della famiglia V-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'V-sit · V-sit Tuck Alternating Leg Extensions';
UPDATE public.exercises SET name = 'V-sit · Tuck', description = 'V-sit e compressioni. Variante: Tuck.', instructions = 'Esegui V-sit · Tuck con controllo, scapole attive e core chiuso. Progressione della famiglia V-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'V-sit · V-sit Tuck';
UPDATE public.exercises SET name = 'V-sit · Wall Compression', description = 'V-sit e compressioni. Variante: Wall Compression.', instructions = 'Esegui V-sit · Wall Compression con controllo, scapole attive e core chiuso. Progressione della famiglia V-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'V-sit · V-sit Wall Compression';
UPDATE public.exercises SET name = 'V-sit', description = 'V-sit e compressioni.', instructions = 'Esegui V-sit con controllo, scapole attive e core chiuso. Progressione della famiglia V-sit. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'V-sit · V-sit';
UPDATE public.exercises SET name = 'Victorian assisted · Advanced Raises', description = 'Victorian assistita agli anelli. Variante: Advanced Raises.', instructions = 'Esegui Victorian assisted · Advanced Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Victorian assisted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Victorian assisted · Victorian Assisted Advanced Raises';
UPDATE public.exercises SET name = 'Victorian assisted · Advanced', description = 'Victorian assistita agli anelli. Variante: Advanced.', instructions = 'Esegui Victorian assisted · Advanced con controllo, scapole attive e core chiuso. Progressione della famiglia Victorian assisted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Victorian assisted · Victorian Assisted Advanced';
UPDATE public.exercises SET name = 'Victorian assisted · Full Raises', description = 'Victorian assistita agli anelli. Variante: Full Raises.', instructions = 'Esegui Victorian assisted · Full Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Victorian assisted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Victorian assisted · Victorian Assisted Full Raises';
UPDATE public.exercises SET name = 'Victorian assisted · Full', description = 'Victorian assistita agli anelli. Variante: Full.', instructions = 'Esegui Victorian assisted · Full con controllo, scapole attive e core chiuso. Progressione della famiglia Victorian assisted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Victorian assisted · Victorian Assisted Full';
UPDATE public.exercises SET name = 'Victorian assisted · One Leg Raises', description = 'Victorian assistita agli anelli. Variante: One Leg Raises.', instructions = 'Esegui Victorian assisted · One Leg Raises con controllo, scapole attive e core chiuso. Progressione della famiglia Victorian assisted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Victorian assisted · Victorian Assisted One Leg Raises';
UPDATE public.exercises SET name = 'Victorian assisted · One Leg', description = 'Victorian assistita agli anelli. Variante: One Leg.', instructions = 'Esegui Victorian assisted · One Leg con controllo, scapole attive e core chiuso. Progressione della famiglia Victorian assisted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Victorian assisted · Victorian Assisted One Leg';
UPDATE public.exercises SET name = 'Victorian assisted · Tuck', description = 'Victorian assistita agli anelli. Variante: Tuck.', instructions = 'Esegui Victorian assisted · Tuck con controllo, scapole attive e core chiuso. Progressione della famiglia Victorian assisted. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Victorian assisted · Victorian Assisted Tuck';
UPDATE public.exercises SET name = 'Warm-up · Cat Cow', description = 'Riscaldamento articolare e attivazione. Variante: Cat Cow.', instructions = 'Esegui Warm-up · Cat Cow con controllo, scapole attive e core chiuso. Progressione della famiglia Warm-up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Warm-up · Cat-Cow';
UPDATE public.exercises SET name = 'Warm-up · Plank Cat Cow', description = 'Riscaldamento articolare e attivazione. Variante: Plank Cat Cow.', instructions = 'Esegui Warm-up · Plank Cat Cow con controllo, scapole attive e core chiuso. Progressione della famiglia Warm-up. Video dimostrativo in arrivo.' WHERE is_public = true AND name = 'Warm-up · Plank Cat-Cow';

-- Pubblici che non sono nel set Drive (vecchio catalogo Forza/Yoga/Stretching palestra, ecc.)
DELETE FROM public.pt_course_step_exercises cse
USING public.exercises e
WHERE cse.exercise_id = e.id
  AND e.is_public = true
  AND e.name NOT IN (
  'Back lever · Advanced Pulls',
  'Back lever · Back Lever Advanced Pulls',
  'Back lever · Advanced',
  'Back lever · Back Lever Advanced',
  'Back lever · Full Pulls',
  'Back lever · Back Lever Full Pulls',
  'Back lever · Full',
  'Back lever · Back Lever Full',
  'Back lever · One Leg Advanced Pulls',
  'Back lever · Back Lever One Leg Advanced Pulls',
  'Back lever · One Leg Advanced',
  'Back lever · Back Lever One Leg Advanced',
  'Back lever · One Leg Pulls',
  'Back lever · Back Lever One Leg Pulls',
  'Back lever · One Leg',
  'Back lever · Back Lever One Leg',
  'Back lever · Straddle Pulls',
  'Back lever · Back Lever Straddle Pulls',
  'Back lever · Straddle',
  'Back lever · Back Lever Straddle',
  'Back lever · Tuck Pulls',
  'Back lever · Back Lever Tuck Pulls',
  'Back lever · Tuck',
  'Back lever · Back Lever Tuck',
  'Back lever · Skin The Cat',
  'Bar muscle up · Box Assisted',
  'Bar muscle up · Box Assisted Muscle Up',
  'Bar muscle up · Chest To Bar Pull Ups',
  'Bar muscle up · L Sit',
  'Bar muscle up · L Sit Muscle Up',
  'Bar muscle up',
  'Bar muscle up · Muscle Up',
  'Core · V Ups',
  'Core · V-Ups',
  'Core · Dynamic Superman',
  'Core · Tuck V Ups',
  'Core · Tuck V-Ups',
  'Core · Crunch',
  'Core · Dragon Flag Full',
  'Core · Dragon Flag One Leg',
  'Core · Dynamic Dragon Flag Full',
  'Core · Dynamic Dragon Flag One Leg',
  'Core · High Plank',
  'Core · Hollow Position',
  'Core · One Arm Plank',
  'Core · Plank',
  'Core · Reverse Crunch',
  'Core · Seated Full Leg Raises',
  'Core · Seated One Leg Raises',
  'Core · Side Plank',
  'Core · Sit Up',
  'Core · Straddle Leg Raises',
  'Core · Straddle One Leg Raises',
  'Core · Superman',
  'Core · Toes To Bar Cross Body Knee To Elbow',
  'Core · Toes To Bar Elbow To Knee',
  'Core · Toes To Bar To L',
  'Core · Toes To Bar Tuck',
  'Core · Toes To Bar',
  'Dip · Bar Dips',
  'Dip · Dips',
  'Dip · Elevated Foot Dips',
  'Dip · Elevated-Foot Dips',
  'Dip · Foot Assisted Dips',
  'Dip · Ring Dips',
  'Dip · Russian Dips',
  'Dip · Supinated Ring Dips',
  'Dragon press · Advanced',
  'Dragon press · Dragon Press Advanced',
  'Dragon press · Full',
  'Dragon press · Dragon Press Full',
  'Dragon press · One Leg',
  'Dragon press · Dragon Press One Leg',
  'Dragon press · Straddle',
  'Dragon press · Dragon Press Straddle',
  'Dragon press · Tuck',
  'Dragon press · Dragon Press Tuck',
  'Front lever · Advanced Pull Up',
  'Front lever · Front Lever Advanced Pull Up',
  'Front lever · Advanced Pulls',
  'Front lever · Front Lever Advanced Pulls',
  'Front lever · Advanced Raises',
  'Front lever · Front Lever Advanced Raises',
  'Front lever · Advanced',
  'Front lever · Front Lever Advanced',
  'Front lever · Full Pull Up',
  'Front lever · Front Lever Full Pull Up',
  'Front lever · Full Pulls',
  'Front lever · Front Lever Full Pulls',
  'Front lever · Full Raises',
  'Front lever · Front Lever Full Raises',
  'Front lever · Full',
  'Front lever · Front Lever Full',
  'Front lever · One Leg Pull Up',
  'Front lever · Front Lever One Leg Pull Up',
  'Front lever · One Leg Pulls',
  'Front lever · Front Lever One Leg Pulls',
  'Front lever · One Leg Raises',
  'Front lever · Front Lever One Leg Raises',
  'Front lever · One Leg',
  'Front lever · Front Lever One Leg',
  'Front lever · Pulses',
  'Front lever · Front Lever Pulses',
  'Front lever · Straddle Pull Up',
  'Front lever · Front Lever Straddle Pull Up',
  'Front lever · Straddle Raises',
  'Front lever · Front Lever Straddle Raises',
  'Front lever · Straddle',
  'Front lever · Front Lever Straddle',
  'Front lever · Touch Advanced',
  'Front lever · Front Lever Touch Advanced',
  'Front lever · Touch Full',
  'Front lever · Front Lever Touch Full',
  'Front lever · Touch One Leg Advanced',
  'Front lever · Front Lever Touch One Leg Advanced',
  'Front lever · Touch Straddle',
  'Front lever · Front Lever Touch Straddle',
  'Front lever · Tuck Pulls',
  'Front lever · Front Lever Tuck Pulls',
  'Front lever · Tuck',
  'Front lever · Front Lever Tuck',
  'Front lever · Ice Cream Maker',
  'Handstand · Back To Wall Handstand Alternating Leg Lifts',
  'Handstand · Diagonal Wall Lean',
  'Handstand · Diagonal Wall Lean Handstand',
  'Handstand · Frog Stand',
  'Handstand · Half Lay',
  'Handstand · Handstand Half Lay',
  'Handstand · One Leg',
  'Handstand · Handstand One Leg',
  'Handstand · Straddle To Full',
  'Handstand · Handstand Straddle To Full',
  'Handstand · Wall Pike Position',
  'Handstand · Handstand Wall Pike Position',
  'Handstand',
  'Handstand · Handstand',
  'Handstand · L Handstand Assisted',
  'Handstand · L-Handstand Assisted',
  'Handstand · L Handstand Kick Ups',
  'Handstand · L-Handstand Kick Ups',
  'Handstand · Pike Position',
  'Handstand · Tripod',
  'Handstand · V Position',
  'Handstand · V-Position',
  'Handstand · Wall Facing Handstand Straddlemp4',
  'Handstand · Wall Facing Handstand Toe Pulls',
  'Handstand · Wall Facing',
  'Handstand · Wall Facing Handstand',
  'Handstand · Wall L Handstand Kick Ups',
  'Handstand · Wall L-Handstand Kick Ups',
  'Handstand · Wall L',
  'Handstand · Wall L-Handstand',
  'Handstand · Wall Tuck Handstand Kick Ups',
  'Handstand · Wall Facing Handstand Alternating Leg Lifts',
  'Handstand · Wall-Facing Handstand Alternating Leg Lifts',
  'Hspu · Back To Wall On Parallettes',
  'Hspu · HSPU Back To Wall On Parallettes',
  'Hspu · Back To Wall',
  'Hspu · HSPU Back To Wall',
  'Hspu · Eccentric',
  'Hspu · HSPU Eccentric',
  'Hspu · On Prallelettes',
  'Hspu · HSPU On Prallelettes',
  'Hspu · Straddle',
  'Hspu · HSPU Straddle',
  'Hspu · Wall Facing On Parallettes',
  'Hspu · HSPU Wall Facing On Parallettes',
  'Hspu · Parallette Pyke Push Up',
  'Hspu · Pyke Push Up',
  'Hspu · Pyke Push-Up',
  'Hspu · V Push Up',
  'Hspu · V-Push Up',
  'Human flag · Front Block',
  'Human flag · Full Raises',
  'Human flag · Human Flag Full Raises',
  'Human flag · Half Lay',
  'Human flag · Human Flag Half Lay',
  'Human flag · Lay Raises',
  'Human flag · Human Flag Lay Raises',
  'Human flag · Straddle Raises',
  'Human flag · Human Flag Straddle Raises',
  'Human flag · Straddle',
  'Human flag · Human Flag Straddle',
  'Human flag',
  'Human flag · Human Flag',
  'Human flag · Lateral Block',
  'Iron cross · Assisted',
  'Iron cross · Iron Cross Assisted',
  'Iron cross · Eccentric',
  'Iron cross · Iron Cross Eccentric',
  'Iron cross · Half',
  'Iron cross · Iron Cross Half',
  'Iron cross · Pulls',
  'Iron cross · Iron Cross Pulls',
  'Iron cross',
  'Iron cross · Iron Cross',
  'L-sit · Alternating Leg L Sit Extension',
  'L-sit · Alternating Leg L-sit Extension',
  'L-sit · Dinamic',
  'L-sit · Dinamic L-sit',
  'L-sit · Advanced',
  'L-sit · L-sit Advanced',
  'L-sit · Full To Straddle',
  'L-sit · L-sit Full To Straddle',
  'L-sit · Tuck',
  'L-sit · L-sit Tuck',
  'L-sit',
  'L-sit · L-sit',
  'L-sit · One Leg',
  'Legs · Alternating Jump Lunges',
  'Legs · Alternating Reverse Lunges',
  'Legs · Bulgarian Split Squat',
  'Legs · Lateral Lunges',
  'Legs · Pistol Box Squat',
  'Legs · Pistol Squat On Ring',
  'Legs · Pistol Squat',
  'Legs · Revers Hyperextension On Box',
  'Legs · Single Leg Box Squat',
  'Legs · Skater Squat',
  'Legs · Squat Jump',
  'Legs · Squat',
  'Legs · Static Lunges',
  'Legs · Sumo Squat',
  'Legs · Wall Assisted Pistol Squat',
  'Maltese · Kneeling Maltese Lean',
  'Maltese · Kneeling Ring Fly',
  'Maltese · Straddle',
  'Maltese · Maltese Straddle',
  'Maltese',
  'Maltese · Maltese',
  'Oap · Australian Archer Pull Up',
  'Oap · Archer Pull Up',
  'Oap · OAC Isometric Assisted',
  'Oap · OAC',
  'Oap · Assisted',
  'Oap · OAP Assisted',
  'Oap · Eccentric',
  'Oap · OAP Eccentric',
  'Oap',
  'Oap · OAP',
  'Oap · Ring Archer Pull Up',
  'Planche · Bent Arm Advanced',
  'Planche · Bent Arm One Leg',
  'Planche · Bent Arm Straddle',
  'Planche · Bent Arm Tuck',
  'Planche · Bent Arm',
  'Planche · Elephant Stand',
  'Planche · Advanced Push Up',
  'Planche · Planche Advanced Push-Up',
  'Planche · Advanced',
  'Planche · Planche Advanced',
  'Planche · Full Press',
  'Planche · Planche Full Press',
  'Planche · Full',
  'Planche · Planche Full',
  'Planche · Lean Push Up',
  'Planche · Planche Lean Push-Up',
  'Planche · Lean Rocks',
  'Planche · Planche Lean Rocks',
  'Planche · Lean',
  'Planche · Planche Lean',
  'Planche · Lift Offs',
  'Planche · Planche Lift-Offs',
  'Planche · Open Advanced',
  'Planche · Planche Open Advanced',
  'Planche · Open Tuck',
  'Planche · Planche Open Tuck',
  'Planche · Straddle Press',
  'Planche · Planche Straddle Press',
  'Planche · Straddle',
  'Planche · Planche Straddle',
  'Planche · Tuck Push Up',
  'Planche · Planche Tuck Push-Up',
  'Planche · Tuck To Advanced',
  'Planche · Planche Tuck To Advanced',
  'Planche · Tuck',
  'Planche · Planche Tuck',
  'Planche · Shoulder Planche Advanced',
  'Planche · Shoulder Planche One Leg',
  'Planche · Shoulder Planche Straddle',
  'Planche · Shoulder Planche Tuck',
  'Planche · Shoulder',
  'Planche · Shoulder Planche',
  'Pull up · Chin Up',
  'Pull up · Chin-Up',
  'Pull up · Close Chin Up',
  'Pull up · Close Chin-Up',
  'Pull up · Close',
  'Pull up · Close Pull Up',
  'Pull up · Eccentric Chin Up',
  'Pull up · Eccentric Chin-Up',
  'Pull up · Eccentric',
  'Pull up · Eccentric Pull Up',
  'Pull up · Iso Chin Up 90°',
  'Pull up · Iso Chin-Up 90°',
  'Pull up · Iso Chin Up',
  'Pull up · Iso Chin-Up',
  'Pull up · Mixed Grip',
  'Pull up · Mixed Grip Pull Up',
  'Pull up · Neutral Grip',
  'Pull up · Neutral Grip Pull Up',
  'Pull up',
  'Pull up · Pull Up',
  'Pull up · Ring',
  'Pull up · Ring Pull Up',
  'Pull up · Wide',
  'Pull up · Wide Pull Up',
  'Pull up · Australian',
  'Pull up · Australian Pull-Up',
  'Pull up · Foot Assisted',
  'Pull up · Foot-Assisted Pull-Up',
  'Pull up · Horizontal',
  'Pull up · Horizontal Pull-Up',
  'Push Up · Archer',
  'Push Up · Archer Push-Ups',
  'Push Up · Decline',
  'Push Up · Decline Push-Ups',
  'Push Up · Diamond',
  'Push Up · Diamond Push-Ups',
  'Push Up · Knee',
  'Push Up · Knee Push-Ups',
  'Push Up · Parallette',
  'Push Up · Parallette Push-Ups',
  'Push Up · Plio',
  'Push Up · Plio Push-Ups',
  'Push Up',
  'Push Up · Push-Ups',
  'Push Up · Ring Flyes',
  'Push Up · Ring',
  'Push Up · Ring Push-Ups',
  'Push Up · Russian',
  'Push Up · Russian Push-Ups',
  'Push Up · Scapular',
  'Push Up · Scapular Push-Ups',
  'Push Up · Staggered',
  'Push Up · Staggered Push-Ups',
  'Push Up · Supinated Ring',
  'Push Up · Supinated Ring Push-Ups',
  'Push Up · Tiger',
  'Push Up · Tiger Push-Ups',
  'Push Up · Wide',
  'Push Up · Wide Push-Ups',
  'Ring muscle up · Eccentric',
  'Ring muscle up · Eccentric Ring Muscle Up',
  'Ring muscle up · False Grip Australian Pull Up',
  'Ring muscle up · False Grip Pull Up',
  'Ring muscle up · Assisted',
  'Ring muscle up · Ring Muscle Up Assisted',
  'Ring muscle up',
  'Ring muscle up · Ring Muscle Up',
  'Stretching · Cobra Stretch',
  'Stretching · Cross Body Shoulder',
  'Stretching · Cross-Body Shoulder',
  'Stretching · Cross Legged Standing Forward Fold',
  'Stretching · Cross-Legged Standing Forward Fold',
  'Stretching · Diagonal Neck',
  'Stretching · Double Knee To Chest',
  'Stretching · Figure Four',
  'Stretching · Lateral Neck',
  'Stretching · Neck Extension',
  'Stretching · Overhead Triceps',
  'Stretching · Pancake',
  'Stretching · Quadriceps Stretch',
  'Stretching · Seated Forward Fold',
  'Stretching · Seated Straddle Side',
  'Stretching · Shoulder Width Standing Forward Fold',
  'Stretching · Shoulder-Width Standing Forward Fold',
  'Stretching · Single Knee To Chest',
  'Stretching · Soulder Flexion',
  'Stretching · Standing Forward Fold',
  'Stretching · Supine Quad Stretch',
  'Stretching · Supine Spinal Twist',
  'Stretching · Wide Leg Standing Forward Fold',
  'Ted · Eccentric',
  'Ted · Eccentric TED',
  'Ted · Half',
  'Ted · Half TED',
  'Ted · Assisted',
  'Ted · TED Assisted',
  'Ted · Iso',
  'Ted · TED Iso',
  'Ted',
  'Ted · TED',
  'V-sit · Straddle',
  'V-sit · V-sit Straddle',
  'V-sit · Tuck Alternating Leg Extensions',
  'V-sit · V-sit Tuck Alternating Leg Extensions',
  'V-sit · Tuck',
  'V-sit · V-sit Tuck',
  'V-sit · Wall Compression',
  'V-sit · V-sit Wall Compression',
  'V-sit',
  'V-sit · V-sit',
  'Victorian assisted · Advanced Raises',
  'Victorian assisted · Victorian Assisted Advanced Raises',
  'Victorian assisted · Advanced',
  'Victorian assisted · Victorian Assisted Advanced',
  'Victorian assisted · Full Raises',
  'Victorian assisted · Victorian Assisted Full Raises',
  'Victorian assisted · Full',
  'Victorian assisted · Victorian Assisted Full',
  'Victorian assisted · One Leg Raises',
  'Victorian assisted · Victorian Assisted One Leg Raises',
  'Victorian assisted · One Leg',
  'Victorian assisted · Victorian Assisted One Leg',
  'Victorian assisted · Tuck',
  'Victorian assisted · Victorian Assisted Tuck',
  'Warm-up · Alternating Arm Swings',
  'Warm-up · Alternative Arm',
  'Warm-up · Backward Arm Circles',
  'Warm-up · Cat Cow',
  'Warm-up · Cat-Cow',
  'Warm-up · Finger Flexion And Extension',
  'Warm-up · Forward Arm Circles',
  'Warm-up · Hops',
  'Warm-up · Jumping Jacks',
  'Warm-up · Kneeling Shoulder Stretch',
  'Warm-up · Kneeling Wrist Stretch',
  'Warm-up · Neck Flexion & Extension',
  'Warm-up · Neck Lateral Flexion',
  'Warm-up · Neck Rotation',
  'Warm-up · Plank Cat Cow',
  'Warm-up · Plank Cat-Cow',
  'Warm-up · Reverse Wrist Stretch',
  'Warm-up · Shoulder Flexion & Extension',
  'Warm-up · Shoulder Opener',
  'Warm-up · Small Arm Circles Overhead',
  'Warm-up · Standing Cross Body Toe Touch',
  'Warm-up · Standing Forward Band',
  'Warm-up · Wrist Extension Stretch',
  'Warm-up · Wrist Flexion',
  'Warm-up · Wrist Rotations On Fists'
  );

DELETE FROM public.exercises
WHERE is_public = true
  AND name NOT IN (
  'Back lever · Advanced Pulls',
  'Back lever · Back Lever Advanced Pulls',
  'Back lever · Advanced',
  'Back lever · Back Lever Advanced',
  'Back lever · Full Pulls',
  'Back lever · Back Lever Full Pulls',
  'Back lever · Full',
  'Back lever · Back Lever Full',
  'Back lever · One Leg Advanced Pulls',
  'Back lever · Back Lever One Leg Advanced Pulls',
  'Back lever · One Leg Advanced',
  'Back lever · Back Lever One Leg Advanced',
  'Back lever · One Leg Pulls',
  'Back lever · Back Lever One Leg Pulls',
  'Back lever · One Leg',
  'Back lever · Back Lever One Leg',
  'Back lever · Straddle Pulls',
  'Back lever · Back Lever Straddle Pulls',
  'Back lever · Straddle',
  'Back lever · Back Lever Straddle',
  'Back lever · Tuck Pulls',
  'Back lever · Back Lever Tuck Pulls',
  'Back lever · Tuck',
  'Back lever · Back Lever Tuck',
  'Back lever · Skin The Cat',
  'Bar muscle up · Box Assisted',
  'Bar muscle up · Box Assisted Muscle Up',
  'Bar muscle up · Chest To Bar Pull Ups',
  'Bar muscle up · L Sit',
  'Bar muscle up · L Sit Muscle Up',
  'Bar muscle up',
  'Bar muscle up · Muscle Up',
  'Core · V Ups',
  'Core · V-Ups',
  'Core · Dynamic Superman',
  'Core · Tuck V Ups',
  'Core · Tuck V-Ups',
  'Core · Crunch',
  'Core · Dragon Flag Full',
  'Core · Dragon Flag One Leg',
  'Core · Dynamic Dragon Flag Full',
  'Core · Dynamic Dragon Flag One Leg',
  'Core · High Plank',
  'Core · Hollow Position',
  'Core · One Arm Plank',
  'Core · Plank',
  'Core · Reverse Crunch',
  'Core · Seated Full Leg Raises',
  'Core · Seated One Leg Raises',
  'Core · Side Plank',
  'Core · Sit Up',
  'Core · Straddle Leg Raises',
  'Core · Straddle One Leg Raises',
  'Core · Superman',
  'Core · Toes To Bar Cross Body Knee To Elbow',
  'Core · Toes To Bar Elbow To Knee',
  'Core · Toes To Bar To L',
  'Core · Toes To Bar Tuck',
  'Core · Toes To Bar',
  'Dip · Bar Dips',
  'Dip · Dips',
  'Dip · Elevated Foot Dips',
  'Dip · Elevated-Foot Dips',
  'Dip · Foot Assisted Dips',
  'Dip · Ring Dips',
  'Dip · Russian Dips',
  'Dip · Supinated Ring Dips',
  'Dragon press · Advanced',
  'Dragon press · Dragon Press Advanced',
  'Dragon press · Full',
  'Dragon press · Dragon Press Full',
  'Dragon press · One Leg',
  'Dragon press · Dragon Press One Leg',
  'Dragon press · Straddle',
  'Dragon press · Dragon Press Straddle',
  'Dragon press · Tuck',
  'Dragon press · Dragon Press Tuck',
  'Front lever · Advanced Pull Up',
  'Front lever · Front Lever Advanced Pull Up',
  'Front lever · Advanced Pulls',
  'Front lever · Front Lever Advanced Pulls',
  'Front lever · Advanced Raises',
  'Front lever · Front Lever Advanced Raises',
  'Front lever · Advanced',
  'Front lever · Front Lever Advanced',
  'Front lever · Full Pull Up',
  'Front lever · Front Lever Full Pull Up',
  'Front lever · Full Pulls',
  'Front lever · Front Lever Full Pulls',
  'Front lever · Full Raises',
  'Front lever · Front Lever Full Raises',
  'Front lever · Full',
  'Front lever · Front Lever Full',
  'Front lever · One Leg Pull Up',
  'Front lever · Front Lever One Leg Pull Up',
  'Front lever · One Leg Pulls',
  'Front lever · Front Lever One Leg Pulls',
  'Front lever · One Leg Raises',
  'Front lever · Front Lever One Leg Raises',
  'Front lever · One Leg',
  'Front lever · Front Lever One Leg',
  'Front lever · Pulses',
  'Front lever · Front Lever Pulses',
  'Front lever · Straddle Pull Up',
  'Front lever · Front Lever Straddle Pull Up',
  'Front lever · Straddle Raises',
  'Front lever · Front Lever Straddle Raises',
  'Front lever · Straddle',
  'Front lever · Front Lever Straddle',
  'Front lever · Touch Advanced',
  'Front lever · Front Lever Touch Advanced',
  'Front lever · Touch Full',
  'Front lever · Front Lever Touch Full',
  'Front lever · Touch One Leg Advanced',
  'Front lever · Front Lever Touch One Leg Advanced',
  'Front lever · Touch Straddle',
  'Front lever · Front Lever Touch Straddle',
  'Front lever · Tuck Pulls',
  'Front lever · Front Lever Tuck Pulls',
  'Front lever · Tuck',
  'Front lever · Front Lever Tuck',
  'Front lever · Ice Cream Maker',
  'Handstand · Back To Wall Handstand Alternating Leg Lifts',
  'Handstand · Diagonal Wall Lean',
  'Handstand · Diagonal Wall Lean Handstand',
  'Handstand · Frog Stand',
  'Handstand · Half Lay',
  'Handstand · Handstand Half Lay',
  'Handstand · One Leg',
  'Handstand · Handstand One Leg',
  'Handstand · Straddle To Full',
  'Handstand · Handstand Straddle To Full',
  'Handstand · Wall Pike Position',
  'Handstand · Handstand Wall Pike Position',
  'Handstand',
  'Handstand · Handstand',
  'Handstand · L Handstand Assisted',
  'Handstand · L-Handstand Assisted',
  'Handstand · L Handstand Kick Ups',
  'Handstand · L-Handstand Kick Ups',
  'Handstand · Pike Position',
  'Handstand · Tripod',
  'Handstand · V Position',
  'Handstand · V-Position',
  'Handstand · Wall Facing Handstand Straddlemp4',
  'Handstand · Wall Facing Handstand Toe Pulls',
  'Handstand · Wall Facing',
  'Handstand · Wall Facing Handstand',
  'Handstand · Wall L Handstand Kick Ups',
  'Handstand · Wall L-Handstand Kick Ups',
  'Handstand · Wall L',
  'Handstand · Wall L-Handstand',
  'Handstand · Wall Tuck Handstand Kick Ups',
  'Handstand · Wall Facing Handstand Alternating Leg Lifts',
  'Handstand · Wall-Facing Handstand Alternating Leg Lifts',
  'Hspu · Back To Wall On Parallettes',
  'Hspu · HSPU Back To Wall On Parallettes',
  'Hspu · Back To Wall',
  'Hspu · HSPU Back To Wall',
  'Hspu · Eccentric',
  'Hspu · HSPU Eccentric',
  'Hspu · On Prallelettes',
  'Hspu · HSPU On Prallelettes',
  'Hspu · Straddle',
  'Hspu · HSPU Straddle',
  'Hspu · Wall Facing On Parallettes',
  'Hspu · HSPU Wall Facing On Parallettes',
  'Hspu · Parallette Pyke Push Up',
  'Hspu · Pyke Push Up',
  'Hspu · Pyke Push-Up',
  'Hspu · V Push Up',
  'Hspu · V-Push Up',
  'Human flag · Front Block',
  'Human flag · Full Raises',
  'Human flag · Human Flag Full Raises',
  'Human flag · Half Lay',
  'Human flag · Human Flag Half Lay',
  'Human flag · Lay Raises',
  'Human flag · Human Flag Lay Raises',
  'Human flag · Straddle Raises',
  'Human flag · Human Flag Straddle Raises',
  'Human flag · Straddle',
  'Human flag · Human Flag Straddle',
  'Human flag',
  'Human flag · Human Flag',
  'Human flag · Lateral Block',
  'Iron cross · Assisted',
  'Iron cross · Iron Cross Assisted',
  'Iron cross · Eccentric',
  'Iron cross · Iron Cross Eccentric',
  'Iron cross · Half',
  'Iron cross · Iron Cross Half',
  'Iron cross · Pulls',
  'Iron cross · Iron Cross Pulls',
  'Iron cross',
  'Iron cross · Iron Cross',
  'L-sit · Alternating Leg L Sit Extension',
  'L-sit · Alternating Leg L-sit Extension',
  'L-sit · Dinamic',
  'L-sit · Dinamic L-sit',
  'L-sit · Advanced',
  'L-sit · L-sit Advanced',
  'L-sit · Full To Straddle',
  'L-sit · L-sit Full To Straddle',
  'L-sit · Tuck',
  'L-sit · L-sit Tuck',
  'L-sit',
  'L-sit · L-sit',
  'L-sit · One Leg',
  'Legs · Alternating Jump Lunges',
  'Legs · Alternating Reverse Lunges',
  'Legs · Bulgarian Split Squat',
  'Legs · Lateral Lunges',
  'Legs · Pistol Box Squat',
  'Legs · Pistol Squat On Ring',
  'Legs · Pistol Squat',
  'Legs · Revers Hyperextension On Box',
  'Legs · Single Leg Box Squat',
  'Legs · Skater Squat',
  'Legs · Squat Jump',
  'Legs · Squat',
  'Legs · Static Lunges',
  'Legs · Sumo Squat',
  'Legs · Wall Assisted Pistol Squat',
  'Maltese · Kneeling Maltese Lean',
  'Maltese · Kneeling Ring Fly',
  'Maltese · Straddle',
  'Maltese · Maltese Straddle',
  'Maltese',
  'Maltese · Maltese',
  'Oap · Australian Archer Pull Up',
  'Oap · Archer Pull Up',
  'Oap · OAC Isometric Assisted',
  'Oap · OAC',
  'Oap · Assisted',
  'Oap · OAP Assisted',
  'Oap · Eccentric',
  'Oap · OAP Eccentric',
  'Oap',
  'Oap · OAP',
  'Oap · Ring Archer Pull Up',
  'Planche · Bent Arm Advanced',
  'Planche · Bent Arm One Leg',
  'Planche · Bent Arm Straddle',
  'Planche · Bent Arm Tuck',
  'Planche · Bent Arm',
  'Planche · Elephant Stand',
  'Planche · Advanced Push Up',
  'Planche · Planche Advanced Push-Up',
  'Planche · Advanced',
  'Planche · Planche Advanced',
  'Planche · Full Press',
  'Planche · Planche Full Press',
  'Planche · Full',
  'Planche · Planche Full',
  'Planche · Lean Push Up',
  'Planche · Planche Lean Push-Up',
  'Planche · Lean Rocks',
  'Planche · Planche Lean Rocks',
  'Planche · Lean',
  'Planche · Planche Lean',
  'Planche · Lift Offs',
  'Planche · Planche Lift-Offs',
  'Planche · Open Advanced',
  'Planche · Planche Open Advanced',
  'Planche · Open Tuck',
  'Planche · Planche Open Tuck',
  'Planche · Straddle Press',
  'Planche · Planche Straddle Press',
  'Planche · Straddle',
  'Planche · Planche Straddle',
  'Planche · Tuck Push Up',
  'Planche · Planche Tuck Push-Up',
  'Planche · Tuck To Advanced',
  'Planche · Planche Tuck To Advanced',
  'Planche · Tuck',
  'Planche · Planche Tuck',
  'Planche · Shoulder Planche Advanced',
  'Planche · Shoulder Planche One Leg',
  'Planche · Shoulder Planche Straddle',
  'Planche · Shoulder Planche Tuck',
  'Planche · Shoulder',
  'Planche · Shoulder Planche',
  'Pull up · Chin Up',
  'Pull up · Chin-Up',
  'Pull up · Close Chin Up',
  'Pull up · Close Chin-Up',
  'Pull up · Close',
  'Pull up · Close Pull Up',
  'Pull up · Eccentric Chin Up',
  'Pull up · Eccentric Chin-Up',
  'Pull up · Eccentric',
  'Pull up · Eccentric Pull Up',
  'Pull up · Iso Chin Up 90°',
  'Pull up · Iso Chin-Up 90°',
  'Pull up · Iso Chin Up',
  'Pull up · Iso Chin-Up',
  'Pull up · Mixed Grip',
  'Pull up · Mixed Grip Pull Up',
  'Pull up · Neutral Grip',
  'Pull up · Neutral Grip Pull Up',
  'Pull up',
  'Pull up · Pull Up',
  'Pull up · Ring',
  'Pull up · Ring Pull Up',
  'Pull up · Wide',
  'Pull up · Wide Pull Up',
  'Pull up · Australian',
  'Pull up · Australian Pull-Up',
  'Pull up · Foot Assisted',
  'Pull up · Foot-Assisted Pull-Up',
  'Pull up · Horizontal',
  'Pull up · Horizontal Pull-Up',
  'Push Up · Archer',
  'Push Up · Archer Push-Ups',
  'Push Up · Decline',
  'Push Up · Decline Push-Ups',
  'Push Up · Diamond',
  'Push Up · Diamond Push-Ups',
  'Push Up · Knee',
  'Push Up · Knee Push-Ups',
  'Push Up · Parallette',
  'Push Up · Parallette Push-Ups',
  'Push Up · Plio',
  'Push Up · Plio Push-Ups',
  'Push Up',
  'Push Up · Push-Ups',
  'Push Up · Ring Flyes',
  'Push Up · Ring',
  'Push Up · Ring Push-Ups',
  'Push Up · Russian',
  'Push Up · Russian Push-Ups',
  'Push Up · Scapular',
  'Push Up · Scapular Push-Ups',
  'Push Up · Staggered',
  'Push Up · Staggered Push-Ups',
  'Push Up · Supinated Ring',
  'Push Up · Supinated Ring Push-Ups',
  'Push Up · Tiger',
  'Push Up · Tiger Push-Ups',
  'Push Up · Wide',
  'Push Up · Wide Push-Ups',
  'Ring muscle up · Eccentric',
  'Ring muscle up · Eccentric Ring Muscle Up',
  'Ring muscle up · False Grip Australian Pull Up',
  'Ring muscle up · False Grip Pull Up',
  'Ring muscle up · Assisted',
  'Ring muscle up · Ring Muscle Up Assisted',
  'Ring muscle up',
  'Ring muscle up · Ring Muscle Up',
  'Stretching · Cobra Stretch',
  'Stretching · Cross Body Shoulder',
  'Stretching · Cross-Body Shoulder',
  'Stretching · Cross Legged Standing Forward Fold',
  'Stretching · Cross-Legged Standing Forward Fold',
  'Stretching · Diagonal Neck',
  'Stretching · Double Knee To Chest',
  'Stretching · Figure Four',
  'Stretching · Lateral Neck',
  'Stretching · Neck Extension',
  'Stretching · Overhead Triceps',
  'Stretching · Pancake',
  'Stretching · Quadriceps Stretch',
  'Stretching · Seated Forward Fold',
  'Stretching · Seated Straddle Side',
  'Stretching · Shoulder Width Standing Forward Fold',
  'Stretching · Shoulder-Width Standing Forward Fold',
  'Stretching · Single Knee To Chest',
  'Stretching · Soulder Flexion',
  'Stretching · Standing Forward Fold',
  'Stretching · Supine Quad Stretch',
  'Stretching · Supine Spinal Twist',
  'Stretching · Wide Leg Standing Forward Fold',
  'Ted · Eccentric',
  'Ted · Eccentric TED',
  'Ted · Half',
  'Ted · Half TED',
  'Ted · Assisted',
  'Ted · TED Assisted',
  'Ted · Iso',
  'Ted · TED Iso',
  'Ted',
  'Ted · TED',
  'V-sit · Straddle',
  'V-sit · V-sit Straddle',
  'V-sit · Tuck Alternating Leg Extensions',
  'V-sit · V-sit Tuck Alternating Leg Extensions',
  'V-sit · Tuck',
  'V-sit · V-sit Tuck',
  'V-sit · Wall Compression',
  'V-sit · V-sit Wall Compression',
  'V-sit',
  'V-sit · V-sit',
  'Victorian assisted · Advanced Raises',
  'Victorian assisted · Victorian Assisted Advanced Raises',
  'Victorian assisted · Advanced',
  'Victorian assisted · Victorian Assisted Advanced',
  'Victorian assisted · Full Raises',
  'Victorian assisted · Victorian Assisted Full Raises',
  'Victorian assisted · Full',
  'Victorian assisted · Victorian Assisted Full',
  'Victorian assisted · One Leg Raises',
  'Victorian assisted · Victorian Assisted One Leg Raises',
  'Victorian assisted · One Leg',
  'Victorian assisted · Victorian Assisted One Leg',
  'Victorian assisted · Tuck',
  'Victorian assisted · Victorian Assisted Tuck',
  'Warm-up · Alternating Arm Swings',
  'Warm-up · Alternative Arm',
  'Warm-up · Backward Arm Circles',
  'Warm-up · Cat Cow',
  'Warm-up · Cat-Cow',
  'Warm-up · Finger Flexion And Extension',
  'Warm-up · Forward Arm Circles',
  'Warm-up · Hops',
  'Warm-up · Jumping Jacks',
  'Warm-up · Kneeling Shoulder Stretch',
  'Warm-up · Kneeling Wrist Stretch',
  'Warm-up · Neck Flexion & Extension',
  'Warm-up · Neck Lateral Flexion',
  'Warm-up · Neck Rotation',
  'Warm-up · Plank Cat Cow',
  'Warm-up · Plank Cat-Cow',
  'Warm-up · Reverse Wrist Stretch',
  'Warm-up · Shoulder Flexion & Extension',
  'Warm-up · Shoulder Opener',
  'Warm-up · Small Arm Circles Overhead',
  'Warm-up · Standing Cross Body Toe Touch',
  'Warm-up · Standing Forward Band',
  'Warm-up · Wrist Extension Stretch',
  'Warm-up · Wrist Flexion',
  'Warm-up · Wrist Rotations On Fists'
  );

DELETE FROM public.pt_course_step_exercises cse
USING public.exercises e
WHERE cse.exercise_id = e.id
  AND e.is_public = true
  AND e.category NOT IN ('Back lever', 'Bar muscle up', 'Core', 'Dip', 'Dragon press', 'Front lever', 'Handstand', 'Hspu', 'Human flag', 'Iron cross', 'L-sit', 'Legs', 'Maltese', 'Oap', 'Planche', 'Pull up', 'Push Up', 'Ring muscle up', 'Stretching', 'Ted', 'V-sit', 'Victorian assisted', 'Warm-up');

DELETE FROM public.exercises
WHERE is_public = true
  AND category NOT IN ('Back lever', 'Bar muscle up', 'Core', 'Dip', 'Dragon press', 'Front lever', 'Handstand', 'Hspu', 'Human flag', 'Iron cross', 'L-sit', 'Legs', 'Maltese', 'Oap', 'Planche', 'Pull up', 'Push Up', 'Ring muscle up', 'Stretching', 'Ted', 'V-sit', 'Victorian assisted', 'Warm-up');
